import Head from 'next/head'
import Image from 'next/image'

import { Box } from '../components/box';
import Header from '../components/header.jsx';
import Sidebar from '../components/sidebar';
import Content from '../components/content.jsx';
// import { Footer } from '../components/footer';

export default function Home() {
  const sidebarItems = [
    {
      title: "",
      icon: "",
      link: "/",
    },
    {
      title: "item 1",
      icon: "",
      link: "/",
    },
    {
      title: "item 2",
      icon: "",
      link: "/",
    },
  ];
  const headerItems = [
    {
      title: "Home",
    },
    {
      title: "Search",
    },
    {
      title: "About",
    }
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Header items={headerItems} />
          <Sidebar items={sidebarItems} />
          <Content />
          {/* <Footer /> */}
        </div>
      </main>
    </>
  )
}